name: testing
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.0 # Added Supabase dependency
  google_maps_flutter: ^2.13.1 # Added google_maps_flutter
  geolocator: ^12.0.0
  flutter_polyline_points: ^2.0.0 # Added flutter_polyline_points for polyline drawing
  flutter_dotenv: ^5.1.0
  mobile_scanner: ^5.1.0 # Added mobile_scanner for QR code scanning
  intl: ^0.18.1  # <-- ADD THIS LINE
  provider: ^6.1.2
  circle_nav_bar: ^2.2.0
  google_fonts: ^6.2.1 # Add this line
  shared_preferences: ^2.2.2   # or latest version
  url_launcher: ^6.2.6 # Added url_launcher for opening URLs
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.6
  rename_app: ^1.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.0


flutter:
  uses-material-design: true

  assets:
    - assets/map_style.txt
    - assets/
    - lib/src/features/user/profile/asset/
    - .env
